local l_ReplicatedStorage_0 = game:GetService("ReplicatedStorage");
return {
    [0] = {
        MaxAnimals = 10, 
        Model = l_ReplicatedStorage_0.Bases.FirstFloor
    }, 
    [1] = {
        MaxAnimals = 10, 
        Model = l_ReplicatedStorage_0.Bases.FirstFloor
    }, 
    [2] = {
        MaxAnimals = 11, 
        Model = l_ReplicatedStorage_0.Bases.SecondFloor
    }, 
    [3] = {
        MaxAnimals = 12, 
        Model = l_ReplicatedStorage_0.Bases.SecondFloor
    }, 
    [4] = {
        MaxAnimals = 13, 
        Model = l_ReplicatedStorage_0.Bases.SecondFloor
    }, 
    [5] = {
        MaxAnimals = 14, 
        Model = l_ReplicatedStorage_0.Bases.SecondFloor
    }, 
    [6] = {
        MaxAnimals = 15, 
        Model = l_ReplicatedStorage_0.Bases.SecondFloor
    }, 
    [7] = {
        MaxAnimals = 16, 
        Model = l_ReplicatedStorage_0.Bases.SecondFloor
    }, 
    [8] = {
        MaxAnimals = 17, 
        Model = l_ReplicatedStorage_0.Bases.SecondFloor
    }, 
    [9] = {
        MaxAnimals = 18, 
        Model = l_ReplicatedStorage_0.Bases.SecondFloor
    }, 
    [10] = {
        MaxAnimals = 19, 
        Model = l_ReplicatedStorage_0.Bases.ThirdFloor
    }, 
    [11] = {
        MaxAnimals = 20, 
        Model = l_ReplicatedStorage_0.Bases.ThirdFloor
    }, 
    [12] = {
        MaxAnimals = 21, 
        Model = l_ReplicatedStorage_0.Bases.ThirdFloor
    }, 
    [13] = {
        MaxAnimals = 22, 
        Model = l_ReplicatedStorage_0.Bases.ThirdFloor
    }, 
    [14] = {
        MaxAnimals = 23, 
        Model = l_ReplicatedStorage_0.Bases.ThirdFloor
    }, 
    [15] = {
        MaxAnimals = 24, 
        Model = l_ReplicatedStorage_0.Bases.ThirdFloor
    }, 
    [16] = {
        MaxAnimals = 25, 
        Model = l_ReplicatedStorage_0.Bases.ThirdFloor
    }, 
    [17] = {
        MaxAnimals = 26, 
        Model = l_ReplicatedStorage_0.Bases.ThirdFloor
    }
};