return {
    Rewards = {
        {
            Type = "Animal", 
            Display = "<font color=\"#E4080A\">Bloodrot</font> Tralalero Tralala<br/><font color=\"#4DFE05\">$10M/s</font>", 
            Icon = "rbxassetid://95251781526770", 
            Index = "Tralalero Tralala", 
            Mutation = "Bloodrot", 
            Weight = 1
        }, 
        {
            Type = "Cash-Pack", 
            Display = "Cash Pack #2", 
            Index = 3290160783, 
            Weight = 55
        }, 
        {
            Type = "Cash-Pack", 
            Display = "Cash Pack #3", 
            Index = 3290160857, 
            Weight = 35
        }, 
        {
            Type = "Item", 
            Display = "Bloodmoon Slap", 
            Icon = "rbxassetid://105241258528205", 
            Index = "Bloodmoon Slap", 
            Weight = 0.5
        }, 
        {
            Type = "Cash-Pack", 
            Display = "Cash Pack #5", 
            Index = 3290161030, 
            Weight = 7.5
        }, 
        {
            Type = "Server-Luck", 
            Icon = "rbxassetid://98903143335097", 
            Display = "2x Server Luck", 
            Index = 1, 
            Weight = 2
        }
    }, 
    AltRewards = {
        [4] = {
            Type = "Item", 
            Display = "Bloodmoon Hammer", 
            Icon = "rbxassetid://96284196754755", 
            Index = "Bloodmoon Hammer", 
            Weight = 0.5
        }
    }
};