return {
    Item = require(script.Item), 
    Event = require(script.Event), 
    Trait = require(script.Trait), 
    Traits = require(script.Traits), 
    Brainrot = require(script.Brainrot), 
    LuckyBlock = require(script.LuckyBlock), 
    BrainrotToCraft = require(script.BrainrotToCraft), 
    BrainrotToTrade = require(script.BrainrotToTrade), 
    Mutation = require(script.Mutation), 
    ServerLuck = require(script.ServerLuck), 
    FuseMachineLuck = require(script.FuseMachineLuck), 
    SnapOptions = require(script.SnapOptions), 
    Update = require(script.Update), 
    BaseSkin = require(script.BaseSkin), 
    StockKey = require(script.StockKey), 
    CalendarDay = require(script.CalendarDay), 
    CalendarDayStatus = require(script.CalendarDayStatus)
};