return {
    Rewards = {
        {
            Type = "Animal", 
            Display = "<font color=\"#f53838\">Cursed</font>\nSecret Lucky Block", 
            Icon = "rbxassetid://109745461401007", 
            Index = "Secret Lucky Block", 
            Mutation = "Cursed", 
            Weight = 0.5
        }, 
        {
            Type = "Cash-Pack", 
            Display = "Cash Pack #2", 
            Index = 3290160783, 
            Weight = 55.5
        }, 
        {
            Type = "Cash-Pack", 
            Display = "Cash Pack #3", 
            Index = 3290160857, 
            Weight = 34
        }, 
        {
            Type = "Item", 
            Display = "Cursed Slap", 
            Icon = "rbxassetid://101392764194646", 
            Index = "Cursed Slap", 
            Weight = 0.5
        }, 
        {
            Type = "Cash-Pack", 
            Display = "Cash Pack #5", 
            Index = 3290161030, 
            Weight = 7.5
        }, 
        {
            Type = "Server-Luck", 
            Icon = "rbxassetid://98903143335097", 
            Display = "2x Server Luck\n15m", 
            Index = 1, 
            Weight = 2
        }
    }, 
    AltRewards = {
        [4] = {
            Type = "Item", 
            Display = "Demon's Head", 
            Icon = "rbxassetid://98312790037177", 
            Index = "Demon's Head", 
            Weight = 0.1
        }
    }
};