return {
    Game = {
        AnimalGanerationModifier = 0.1, 
        OfflineMaxTime = {
            [0] = 60, 
            [1] = 120
        }
    }, 
    Plot = {
        AnimalPodiums = 10
    }, 
    Animal = {
        PriceModifier = 1, 
        SellModifier = 0.5
    }, 
    RoadSpawn = {
        AnimalSpeed = 10, 
        SpawnEvery = 3, 
        PittyList = {
            {
                "Legendary", 
                300
            }, 
            {
                "Mythic", 
                900
            }
        }
    }, 
    BlockBase = {
        Price = 0, 
        Duration = 60
    }, 
    BlockBaseDelay = {
        Duration = 0
    }, 
    Milestones = {
        [1] = {
            RequiredLikes = 250, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [2] = {
            RequiredLikes = 700, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [3] = {
            RequiredLikes = 1500, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [4] = {
            RequiredLikes = 2500, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [5] = {
            RequiredLikes = 5000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [6] = {
            RequiredLikes = 7000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [7] = {
            RequiredLikes = 8500, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [8] = {
            RequiredLikes = 10000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [9] = {
            RequiredLikes = 12500, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [10] = {
            RequiredLikes = 15000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [11] = {
            RequiredLikes = 17500, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [12] = {
            RequiredLikes = 20000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [13] = {
            RequiredLikes = 25000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [14] = {
            RequiredLikes = 30000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [15] = {
            RequiredLikes = 35000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [16] = {
            RequiredLikes = 40000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [17] = {
            RequiredLikes = 45000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [18] = {
            RequiredLikes = 50000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [19] = {
            RequiredLikes = 55000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [20] = {
            RequiredLikes = 60000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [21] = {
            RequiredLikes = 65000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [22] = {
            RequiredLikes = 70000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [23] = {
            RequiredLikes = 75000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [24] = {
            RequiredLikes = 80000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [25] = {
            RequiredLikes = 85000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [26] = {
            RequiredLikes = 90000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [27] = {
            RequiredLikes = 95000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [28] = {
            RequiredLikes = 100000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [29] = {
            RequiredLikes = 105000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [30] = {
            RequiredLikes = 110000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [31] = {
            RequiredLikes = 125000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [32] = {
            RequiredLikes = 150000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [33] = {
            RequiredLikes = 175000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [34] = {
            RequiredLikes = 200000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [35] = {
            RequiredLikes = 225000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [36] = {
            RequiredLikes = 250000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [37] = {
            RequiredLikes = 275000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [38] = {
            RequiredLikes = 300000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [39] = {
            RequiredLikes = 325000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [40] = {
            RequiredLikes = 350000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [41] = {
            RequiredLikes = 375000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [42] = {
            RequiredLikes = 400000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [43] = {
            RequiredLikes = 425000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [44] = {
            RequiredLikes = 450000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [45] = {
            RequiredLikes = 475000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [46] = {
            RequiredLikes = 500000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [47] = {
            RequiredLikes = 525000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [48] = {
            RequiredLikes = 550000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [49] = {
            RequiredLikes = 575000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [50] = {
            RequiredLikes = 600000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [51] = {
            RequiredLikes = 625000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [52] = {
            RequiredLikes = 650000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [53] = {
            RequiredLikes = 675000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [54] = {
            RequiredLikes = 700000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [55] = {
            RequiredLikes = 725000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [56] = {
            RequiredLikes = 750000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [57] = {
            RequiredLikes = 775000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [58] = {
            RequiredLikes = 800000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [59] = {
            RequiredLikes = 825000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [60] = {
            RequiredLikes = 850000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [61] = {
            RequiredLikes = 875000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [62] = {
            RequiredLikes = 900000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [63] = {
            RequiredLikes = 925000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [64] = {
            RequiredLikes = 950000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [65] = {
            RequiredLikes = 975000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [66] = {
            RequiredLikes = 1000000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [67] = {
            RequiredLikes = 1025000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [68] = {
            RequiredLikes = 1050000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [69] = {
            RequiredLikes = 1075000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [70] = {
            RequiredLikes = 1100000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [71] = {
            RequiredLikes = 1125000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [72] = {
            RequiredLikes = 1150000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [73] = {
            RequiredLikes = 1175000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [74] = {
            RequiredLikes = 1200000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [75] = {
            RequiredLikes = 1225000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [76] = {
            RequiredLikes = 1250000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [77] = {
            RequiredLikes = 1275000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [78] = {
            RequiredLikes = 1300000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [79] = {
            RequiredLikes = 1325000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [80] = {
            RequiredLikes = 1350000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [81] = {
            RequiredLikes = 1375000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [82] = {
            RequiredLikes = 1400000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [83] = {
            RequiredLikes = 1425000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [84] = {
            RequiredLikes = 1450000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [85] = {
            RequiredLikes = 1475000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [86] = {
            RequiredLikes = 1500000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [87] = {
            RequiredLikes = 1525000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [88] = {
            RequiredLikes = 1550000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [89] = {
            RequiredLikes = 1575000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [90] = {
            RequiredLikes = 1600000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [91] = {
            RequiredLikes = 1625000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [92] = {
            RequiredLikes = 1650000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [93] = {
            RequiredLikes = 1675000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [94] = {
            RequiredLikes = 1700000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [95] = {
            RequiredLikes = 1725000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [96] = {
            RequiredLikes = 1750000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [97] = {
            RequiredLikes = 1775000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [98] = {
            RequiredLikes = 1800000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [99] = {
            RequiredLikes = 1825000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [100] = {
            RequiredLikes = 1850000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [101] = {
            RequiredLikes = 1875000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [102] = {
            RequiredLikes = 1900000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [103] = {
            RequiredLikes = 1925000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [104] = {
            RequiredLikes = 1950000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [105] = {
            RequiredLikes = 1975000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [106] = {
            RequiredLikes = 2000000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [107] = {
            RequiredLikes = 2025000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [108] = {
            RequiredLikes = 2050000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [109] = {
            RequiredLikes = 2075000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [110] = {
            RequiredLikes = 2100000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [111] = {
            RequiredLikes = 2125000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [112] = {
            RequiredLikes = 2150000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [113] = {
            RequiredLikes = 2175000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [114] = {
            RequiredLikes = 2200000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [115] = {
            RequiredLikes = 2225000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [116] = {
            RequiredLikes = 2250000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [117] = {
            RequiredLikes = 2275000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [118] = {
            RequiredLikes = 2300000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [119] = {
            RequiredLikes = 2325000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [120] = {
            RequiredLikes = 2350000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [121] = {
            RequiredLikes = 2375000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [122] = {
            RequiredLikes = 2400000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [123] = {
            RequiredLikes = 2425000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [124] = {
            RequiredLikes = 2450000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [125] = {
            RequiredLikes = 2475000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [126] = {
            RequiredLikes = 2500000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [127] = {
            RequiredLikes = 2525000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [128] = {
            RequiredLikes = 2550000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [129] = {
            RequiredLikes = 2575000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [130] = {
            RequiredLikes = 2600000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [131] = {
            RequiredLikes = 2625000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [132] = {
            RequiredLikes = 2650000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [133] = {
            RequiredLikes = 2675000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [134] = {
            RequiredLikes = 2700000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [135] = {
            RequiredLikes = 2725000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [136] = {
            RequiredLikes = 2750000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [137] = {
            RequiredLikes = 2775000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [138] = {
            RequiredLikes = 2800000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [139] = {
            RequiredLikes = 2825000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [140] = {
            RequiredLikes = 2850000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [141] = {
            RequiredLikes = 2875000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [142] = {
            RequiredLikes = 2900000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [143] = {
            RequiredLikes = 2925000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [144] = {
            RequiredLikes = 2950000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [145] = {
            RequiredLikes = 2975000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [146] = {
            RequiredLikes = 3000000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [147] = {
            RequiredLikes = 3025000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [148] = {
            RequiredLikes = 3050000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [149] = {
            RequiredLikes = 3075000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [150] = {
            RequiredLikes = 3100000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [151] = {
            RequiredLikes = 3150000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [152] = {
            RequiredLikes = 3200000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [153] = {
            RequiredLikes = 3250000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [154] = {
            RequiredLikes = 3300000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [155] = {
            RequiredLikes = 3350000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [156] = {
            RequiredLikes = 3400000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [157] = {
            RequiredLikes = 3450000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [158] = {
            RequiredLikes = 3500000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [159] = {
            RequiredLikes = 3550000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [160] = {
            RequiredLikes = 3600000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [161] = {
            RequiredLikes = 3650000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [162] = {
            RequiredLikes = 3700000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [163] = {
            RequiredLikes = 3750000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [164] = {
            RequiredLikes = 3800000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [165] = {
            RequiredLikes = 3850000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [166] = {
            RequiredLikes = 3900000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [167] = {
            RequiredLikes = 3950000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [168] = {
            RequiredLikes = 4000000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [169] = {
            RequiredLikes = 4050000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [170] = {
            RequiredLikes = 4100000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [171] = {
            RequiredLikes = 4150000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [172] = {
            RequiredLikes = 4200000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [173] = {
            RequiredLikes = 4250000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [174] = {
            RequiredLikes = 4300000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [175] = {
            RequiredLikes = 4350000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [176] = {
            RequiredLikes = 4400000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [177] = {
            RequiredLikes = 4450000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [178] = {
            RequiredLikes = 4500000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [179] = {
            RequiredLikes = 4550000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [180] = {
            RequiredLikes = 4600000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [181] = {
            RequiredLikes = 4650000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [182] = {
            RequiredLikes = 4700000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [183] = {
            RequiredLikes = 4750000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [184] = {
            RequiredLikes = 4800000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [185] = {
            RequiredLikes = 4850000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [186] = {
            RequiredLikes = 4900000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [187] = {
            RequiredLikes = 4950000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [188] = {
            RequiredLikes = 5000000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [189] = {
            RequiredLikes = 5050000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [190] = {
            RequiredLikes = 5100000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [191] = {
            RequiredLikes = 5150000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [192] = {
            RequiredLikes = 5200000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [193] = {
            RequiredLikes = 5250000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [194] = {
            RequiredLikes = 5300000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [195] = {
            RequiredLikes = 5350000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [196] = {
            RequiredLikes = 5400000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [197] = {
            RequiredLikes = 5450000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [198] = {
            RequiredLikes = 5500000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [199] = {
            RequiredLikes = 5550000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [200] = {
            RequiredLikes = 5600000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [201] = {
            RequiredLikes = 5650000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [202] = {
            RequiredLikes = 5700000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [203] = {
            RequiredLikes = 5750000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [204] = {
            RequiredLikes = 5800000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [205] = {
            RequiredLikes = 5850000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [206] = {
            RequiredLikes = 5900000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [207] = {
            RequiredLikes = 5950000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [208] = {
            RequiredLikes = 6000000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [209] = {
            RequiredLikes = 6050000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [210] = {
            RequiredLikes = 6100000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [211] = {
            RequiredLikes = 6150000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [212] = {
            RequiredLikes = 6200000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [213] = {
            RequiredLikes = 6250000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [214] = {
            RequiredLikes = 6300000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [215] = {
            RequiredLikes = 6350000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [216] = {
            RequiredLikes = 6400000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [217] = {
            RequiredLikes = 6450000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [218] = {
            RequiredLikes = 6500000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [219] = {
            RequiredLikes = 6550000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [220] = {
            RequiredLikes = 6600000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [221] = {
            RequiredLikes = 6650000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [222] = {
            RequiredLikes = 6700000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [223] = {
            RequiredLikes = 6750000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [224] = {
            RequiredLikes = 6800000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [225] = {
            RequiredLikes = 6850000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [226] = {
            RequiredLikes = 6900000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [227] = {
            RequiredLikes = 6950000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [228] = {
            RequiredLikes = 7000000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [229] = {
            RequiredLikes = 7050000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [230] = {
            RequiredLikes = 7100000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [231] = {
            RequiredLikes = 7150000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [232] = {
            RequiredLikes = 7200000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [233] = {
            RequiredLikes = 7250000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [234] = {
            RequiredLikes = 7300000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [235] = {
            RequiredLikes = 7350000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [236] = {
            RequiredLikes = 7400000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [237] = {
            RequiredLikes = 7450000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [238] = {
            RequiredLikes = 7500000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [239] = {
            RequiredLikes = 7550000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [240] = {
            RequiredLikes = 7600000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [241] = {
            RequiredLikes = 7650000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [242] = {
            RequiredLikes = 7700000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [243] = {
            RequiredLikes = 7750000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [244] = {
            RequiredLikes = 7800000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [245] = {
            RequiredLikes = 7850000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [246] = {
            RequiredLikes = 7900000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [247] = {
            RequiredLikes = 7950000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [248] = {
            RequiredLikes = 8000000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [249] = {
            RequiredLikes = 8050000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [250] = {
            RequiredLikes = 8100000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [251] = {
            RequiredLikes = 8150000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [252] = {
            RequiredLikes = 8200000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [253] = {
            RequiredLikes = 8250000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [254] = {
            RequiredLikes = 8300000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [255] = {
            RequiredLikes = 8350000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [256] = {
            RequiredLikes = 8400000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [257] = {
            RequiredLikes = 8450000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [258] = {
            RequiredLikes = 8500000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [259] = {
            RequiredLikes = 8550000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [260] = {
            RequiredLikes = 8600000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [261] = {
            RequiredLikes = 8650000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [262] = {
            RequiredLikes = 8700000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [263] = {
            RequiredLikes = 8750000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [264] = {
            RequiredLikes = 8800000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [265] = {
            RequiredLikes = 8850000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [266] = {
            RequiredLikes = 8900000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [267] = {
            RequiredLikes = 8950000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [268] = {
            RequiredLikes = 9000000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [269] = {
            RequiredLikes = 9050000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [270] = {
            RequiredLikes = 9100000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [271] = {
            RequiredLikes = 9150000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [272] = {
            RequiredLikes = 9200000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [273] = {
            RequiredLikes = 9250000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [274] = {
            RequiredLikes = 9300000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [275] = {
            RequiredLikes = 9350000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [276] = {
            RequiredLikes = 9400000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [277] = {
            RequiredLikes = 9450000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [278] = {
            RequiredLikes = 9500000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [279] = {
            RequiredLikes = 9550000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [280] = {
            RequiredLikes = 9600000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [281] = {
            RequiredLikes = 9650000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [282] = {
            RequiredLikes = 9700000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [283] = {
            RequiredLikes = 9750000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [284] = {
            RequiredLikes = 9800000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [285] = {
            RequiredLikes = 9850000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [286] = {
            RequiredLikes = 9900000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [287] = {
            RequiredLikes = 9950000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [288] = {
            RequiredLikes = 10000000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [289] = {
            RequiredLikes = 10050000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [290] = {
            RequiredLikes = 10100000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [291] = {
            RequiredLikes = 10150000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [292] = {
            RequiredLikes = 10200000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [293] = {
            RequiredLikes = 10250000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [294] = {
            RequiredLikes = 10300000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [295] = {
            RequiredLikes = 10350000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [296] = {
            RequiredLikes = 10400000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [297] = {
            RequiredLikes = 10450000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [298] = {
            RequiredLikes = 10500000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [299] = {
            RequiredLikes = 10550000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [300] = {
            RequiredLikes = 10600000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [301] = {
            RequiredLikes = 10650000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [302] = {
            RequiredLikes = 10700000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [303] = {
            RequiredLikes = 10750000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [304] = {
            RequiredLikes = 10800000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [305] = {
            RequiredLikes = 10850000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [306] = {
            RequiredLikes = 10900000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [307] = {
            RequiredLikes = 10950000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [308] = {
            RequiredLikes = 11000000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [309] = {
            RequiredLikes = 11050000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [310] = {
            RequiredLikes = 11100000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [311] = {
            RequiredLikes = 11150000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [312] = {
            RequiredLikes = 11200000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [313] = {
            RequiredLikes = 11250000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [314] = {
            RequiredLikes = 11300000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [315] = {
            RequiredLikes = 11350000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [316] = {
            RequiredLikes = 11400000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [317] = {
            RequiredLikes = 11450000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [318] = {
            RequiredLikes = 11500000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [319] = {
            RequiredLikes = 11550000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [320] = {
            RequiredLikes = 11600000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [321] = {
            RequiredLikes = 11650000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [322] = {
            RequiredLikes = 11700000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [323] = {
            RequiredLikes = 11750000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [324] = {
            RequiredLikes = 11800000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [325] = {
            RequiredLikes = 11850000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [326] = {
            RequiredLikes = 11900000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [327] = {
            RequiredLikes = 11950000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [328] = {
            RequiredLikes = 12000000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [329] = {
            RequiredLikes = 12050000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [330] = {
            RequiredLikes = 12100000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [331] = {
            RequiredLikes = 12150000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [332] = {
            RequiredLikes = 12200000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [333] = {
            RequiredLikes = 12250000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [334] = {
            RequiredLikes = 12300000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [335] = {
            RequiredLikes = 12350000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [336] = {
            RequiredLikes = 12400000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [337] = {
            RequiredLikes = 12450000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [338] = {
            RequiredLikes = 12500000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [339] = {
            RequiredLikes = 12550000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [340] = {
            RequiredLikes = 12600000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [341] = {
            RequiredLikes = 12650000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [342] = {
            RequiredLikes = 12700000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [343] = {
            RequiredLikes = 12750000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [344] = {
            RequiredLikes = 12800000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [345] = {
            RequiredLikes = 12850000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [346] = {
            RequiredLikes = 12900000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [347] = {
            RequiredLikes = 12950000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [348] = {
            RequiredLikes = 13000000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [349] = {
            RequiredLikes = 13050000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [350] = {
            RequiredLikes = 13100000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [351] = {
            RequiredLikes = 13150000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [352] = {
            RequiredLikes = 13200000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [353] = {
            RequiredLikes = 13250000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [354] = {
            RequiredLikes = 13300000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [355] = {
            RequiredLikes = 13350000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [356] = {
            RequiredLikes = 13400000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [357] = {
            RequiredLikes = 13450000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [358] = {
            RequiredLikes = 13500000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [359] = {
            RequiredLikes = 13550000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [360] = {
            RequiredLikes = 13600000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [361] = {
            RequiredLikes = 13650000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [362] = {
            RequiredLikes = 13700000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [363] = {
            RequiredLikes = 13750000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [364] = {
            RequiredLikes = 13800000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [365] = {
            RequiredLikes = 13850000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [366] = {
            RequiredLikes = 13900000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [367] = {
            RequiredLikes = 13950000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [368] = {
            RequiredLikes = 14000000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [369] = {
            RequiredLikes = 14050000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [370] = {
            RequiredLikes = 14100000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [371] = {
            RequiredLikes = 14150000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [372] = {
            RequiredLikes = 14200000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [373] = {
            RequiredLikes = 14250000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [374] = {
            RequiredLikes = 14300000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [375] = {
            RequiredLikes = 14350000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [376] = {
            RequiredLikes = 14400000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [377] = {
            RequiredLikes = 14450000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [378] = {
            RequiredLikes = 14500000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [379] = {
            RequiredLikes = 14550000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [380] = {
            RequiredLikes = 14600000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [381] = {
            RequiredLikes = 14650000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [382] = {
            RequiredLikes = 14700000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [383] = {
            RequiredLikes = 14750000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [384] = {
            RequiredLikes = 14800000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [385] = {
            RequiredLikes = 14850000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [386] = {
            RequiredLikes = 14900000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [387] = {
            RequiredLikes = 14950000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [388] = {
            RequiredLikes = 15000000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [389] = {
            RequiredLikes = 15050000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [390] = {
            RequiredLikes = 15100000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [391] = {
            RequiredLikes = 15150000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [392] = {
            RequiredLikes = 15200000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [393] = {
            RequiredLikes = 15250000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [394] = {
            RequiredLikes = 15300000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [395] = {
            RequiredLikes = 15350000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [396] = {
            RequiredLikes = 15400000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [397] = {
            RequiredLikes = 15450000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [398] = {
            RequiredLikes = 15500000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [399] = {
            RequiredLikes = 15550000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }, 
        [400] = {
            RequiredLikes = 15600000, 
            RewardText = "Brainrot God", 
            RewardType = "Animal", 
            RewardValue = {
                ["Cocofanto Elefanto"] = 0.75, 
                ["Tralalero Tralala"] = 0.25
            }
        }
    }
};