local l_ReplicatedStorage_0 = game:GetService("ReplicatedStorage");
local _ = require(l_ReplicatedStorage_0.Shared.Updates);
return {
    ["Mythic Lucky Block"] = {
        ProductId = 3329528158, 
        Timer = 600, 
        Animals = {
            {
                Name = "Spioniro Golubiro", 
                Chance = 37
            }, 
            {
                Name = "Zibra Zubra Zibralini", 
                Chance = 30
            }, 
            {
                Name = "Tigrilini Watermelini", 
                Chance = 20
            }, 
            {
                Name = "Carrotini Brainini", 
                Chance = 10
            }, 
            {
                Name = "Bananito Bandito", 
                Chance = 3
            }
        }
    }, 
    ["Brainrot God Lucky Block"] = {
        ProductId = 3329527999, 
        Timer = 900, 
        Animals = {
            {
                Name = "Tigroligre Frutonni", 
                Chance = 54
            }, 
            {
                Name = "Orcalero Orcala", 
                Chance = 30
            }, 
            {
                Name = "Bulbito Bandito Traktorito", 
                Chance = 10
            }, 
            {
                Name = "Mastodontico Telepiedone", 
                Chance = 5
            }, 
            {
                Name = "Pop Pop Sahur", 
                Chance = 1
            }
        }
    }, 
    ["Secret Lucky Block"] = {
        ProductId = 3329528437, 
        Timer = 1800, 
        Animals = {
            {
                Name = "Torrtuginni Dragonfrutini", 
                Chance = 74.5
            }, 
            {
                Name = "Pot Hotspot", 
                Chance = 21
            }, 
            {
                Name = "Esok Sekolah", 
                Chance = 3
            }, 
            {
                Name = "Spaghetti Tualetti", 
                Chance = 1
            }, 
            {
                Name = "La Secret Combinasion", 
                Chance = 0.5
            }
        }
    }, 
    ["Admin Lucky Block"] = {
        Timer = 0, 
        Animals = {
            {
                Name = "Carloo"
            }, 
            {
                Name = "Alessio"
            }, 
            {
                Name = "Los Bombinitos"
            }, 
            {
                Name = "Crabbo Limonetta"
            }, 
            {
                Name = "Blackhole Goat"
            }, 
            {
                Name = "Guerriro Digitale"
            }, 
            {
                Name = "67"
            }, 
            {
                Name = "La Grande Combinasion"
            }
        }
    }, 
    ["Taco Lucky Block"] = {
        Timer = 0, 
        Animals = {
            {
                Name = "Chihuanini Taconini"
            }, 
            {
                Name = "Gattito Tacoto"
            }, 
            {
                Name = "Los Tipi Tacos"
            }, 
            {
                Name = "Quesadilla Crocodila"
            }, 
            {
                Name = "Burrito Bandito"
            }, 
            {
                Name = "Los Nooo My Hotspotsitos"
            }
        }
    }, 
    ["Los Lucky Blocks"] = {
        Timer = 0, 
        Animals = {
            {
                Name = "Los Bombinitos"
            }, 
            {
                Name = "Los Tungtungtungcitos"
            }, 
            {
                Name = "Los Orcalitos"
            }, 
            {
                Name = "Los Tipi Tacos"
            }, 
            {
                Name = "Los Tortus"
            }, 
            {
                Name = "Los Jobcitos"
            }, 
            {
                Name = "Los Combinasionas"
            }, 
            {
                Name = "Los 67"
            }
        }
    }, 
    ["Spooky Lucky Block"] = {
        Timer = 0, 
        Animals = {
            {
                Name = "Mummy Ambalabu"
            }, 
            {
                Name = "Cappuccino Clownino"
            }, 
            {
                Name = "Jackorilla"
            }, 
            {
                Name = "Pumpkini Spyderini"
            }, 
            {
                Name = "Trickolino"
            }, 
            {
                Name = "Telemorte"
            }, 
            {
                Name = "Los Spooky Combinasionas"
            }, 
            {
                Name = "La Casa Boo"
            }
        }
    }, 
    ["Los Taco Blocks"] = {
        Timer = 0, 
        Animals = {
            {
                Name = "Los Chihuaninis"
            }, 
            {
                Name = "Los Gattitos"
            }, 
            {
                Name = "Los Cucarachas"
            }, 
            {
                Name = "Los Quesadillas"
            }, 
            {
                Name = "Los Burritos"
            }
        }
    }, 
    ["Festive Lucky Block"] = {
        Timer = 0, 
        Animals = {
            {
                Name = "Chrismasmamat"
            }, 
            {
                Name = "Pandanini Frostini"
            }, 
            {
                Name = "Triplito Tralaleritos"
            }, 
            {
                Name = "Santa Hotspot"
            }, 
            {
                Name = "Los 25"
            }, 
            {
                Name = "Chimnino"
            }, 
            {
                Name = "La Ginger Sekolah"
            }, 
            {
                Name = "Reinito Sleighito"
            }
        }
    }, 
    ["Premium Festive Lucky Block"] = {
        Timer = 0, 
        Animals = {
            {
                Name = "Chrismasmamat", 
                Chance = 30.9
            }, 
            {
                Name = "Pandanini Frostini", 
                Chance = 30
            }, 
            {
                Name = "Triplito Tralaleritos", 
                Chance = 25
            }, 
            {
                Name = "Santa Hotspot", 
                Chance = 10
            }, 
            {
                Name = "Los 25", 
                Chance = 2.5
            }, 
            {
                Name = "Chimnino", 
                Chance = 1
            }, 
            {
                Name = "La Ginger Sekolah", 
                Chance = 0.5
            }, 
            {
                Name = "Reinito Sleighito", 
                Chance = 0.1
            }
        }
    }
};