return {
    Gold = {
        DisplayText = "Gold", 
        DisplayWithRichText = "<font color=\"#FFDE59\">Gold</font>", 
        Order = 2, 
        Weight = 7, 
        Modifier = 0.25, 
        MainColor = Color3.fromRGB(255, 222, 89), 
        Icon = "rbxassetid://136133057822407", 
        Palettes = {
            [1] = {
                [1] = Color3.fromRGB(237, 178, 0), 
                [2] = Color3.fromRGB(237, 194, 86), 
                [3] = Color3.fromRGB(215, 111, 1), 
                [4] = Color3.fromRGB(139, 74, 0), 
                [5] = Color3.fromRGB(255, 164, 164), 
                [6] = Color3.fromRGB(255, 244, 190)
            }, 
            [2] = {
                [1] = Color3.fromRGB(237, 178, 0), 
                [2] = Color3.fromRGB(237, 194, 86), 
                [3] = Color3.fromRGB(215, 111, 1), 
                [4] = Color3.fromRGB(139, 74, 0), 
                [5] = Color3.fromRGB(237, 194, 86), 
                [6] = Color3.fromRGB(255, 251, 131), 
                [7] = Color3.fromRGB(255, 178, 0), 
                [8] = Color3.fromRGB(215, 111, 1)
            }
        }
    }, 
    Diamond = {
        DisplayText = "Diamond", 
        DisplayWithRichText = "<font color=\"#25C4FE\">Diamond</font>", 
        Order = 3, 
        Weight = 3, 
        Modifier = 0.5, 
        MainColor = Color3.fromRGB(37, 196, 254), 
        Icon = "rbxassetid://100875709547015", 
        Palettes = {
            [1] = {
                [1] = Color3.fromRGB(37, 196, 254), 
                [2] = Color3.fromRGB(116, 212, 254), 
                [3] = Color3.fromRGB(28, 137, 254), 
                [4] = Color3.fromRGB(21, 64, 254), 
                [5] = Color3.fromRGB(160, 162, 254), 
                [6] = Color3.fromRGB(176, 255, 252)
            }, 
            [2] = {
                [1] = Color3.fromRGB(37, 196, 254), 
                [2] = Color3.fromRGB(116, 212, 254), 
                [3] = Color3.fromRGB(28, 137, 254), 
                [4] = Color3.fromRGB(21, 64, 254), 
                [5] = Color3.fromRGB(116, 212, 254), 
                [6] = Color3.fromRGB(116, 212, 254), 
                [7] = Color3.fromRGB(37, 196, 254), 
                [8] = Color3.fromRGB(28, 137, 254)
            }
        }
    }, 
    Bloodrot = {
        DisplayText = "Bloodrot", 
        DisplayWithRichText = "<font color=\"#8A3B3C\">Bloodrot</font>", 
        Modifier = 1, 
        MainColor = Color3.fromRGB(145, 0, 27), 
        Icon = "rbxassetid://75212036784031", 
        Palettes = {
            [1] = {
                [1] = Color3.fromRGB(145, 0, 27), 
                [2] = Color3.fromRGB(154, 94, 100), 
                [3] = Color3.fromRGB(75, 0, 7), 
                [4] = Color3.fromRGB(72, 0, 2), 
                [5] = Color3.fromRGB(121, 112, 112), 
                [6] = Color3.fromRGB(255, 152, 154)
            }, 
            [2] = {
                [1] = Color3.fromRGB(145, 0, 27), 
                [2] = Color3.fromRGB(154, 94, 100), 
                [3] = Color3.fromRGB(75, 0, 7), 
                [4] = Color3.fromRGB(72, 0, 2), 
                [5] = Color3.fromRGB(195, 98, 100), 
                [6] = Color3.fromRGB(195, 98, 100), 
                [7] = Color3.fromRGB(145, 0, 27), 
                [8] = Color3.fromRGB(75, 0, 7)
            }
        }
    }, 
    Rainbow = {
        DisplayText = "Rainbow", 
        DisplayWithRichText = "<font color=\"#ff00fb\">Rainbow</font>", 
        Order = 4, 
        GradientPreset = "Rainbow", 
        Weight = 0.2, 
        Modifier = 9, 
        MainColor = Color3.fromRGB(255, 0, 251), 
        Icon = "rbxassetid://83078714090192", 
        Palettes = {
            [1] = {
                [1] = Color3.fromRGB(255, 0, 4), 
                [2] = Color3.fromRGB(255, 0, 242), 
                [3] = Color3.fromRGB(0, 132, 255), 
                [4] = Color3.fromRGB(17, 255, 0), 
                [5] = Color3.fromRGB(251, 255, 0), 
                [6] = Color3.fromRGB(0, 255, 255)
            }, 
            [2] = {
                [1] = Color3.fromRGB(255, 0, 4), 
                [2] = Color3.fromRGB(255, 0, 242), 
                [3] = Color3.fromRGB(0, 132, 255), 
                [4] = Color3.fromRGB(17, 255, 0), 
                [5] = Color3.fromRGB(227, 225, 230), 
                [6] = Color3.fromRGB(227, 225, 230), 
                [7] = Color3.fromRGB(231, 64, 64), 
                [8] = Color3.fromRGB(24, 49, 159)
            }
        }
    }, 
    Candy = {
        DisplayText = "Candy", 
        DisplayWithRichText = "<font color=\"#ff46f6\">Candy</font>", 
        Order = 5, 
        Modifier = 3, 
        MainColor = Color3.fromRGB(255, 70, 246), 
        Icon = "rbxassetid://84797673698685", 
        Palettes = {
            [1] = {
                [1] = Color3.fromRGB(255, 182, 255), 
                [2] = Color3.fromRGB(255, 105, 180), 
                [3] = Color3.fromRGB(255, 0, 251), 
                [4] = Color3.fromRGB(200, 0, 180), 
                [5] = Color3.fromRGB(255, 146, 246), 
                [6] = Color3.fromRGB(255, 160, 225)
            }, 
            [2] = {
                [1] = Color3.fromRGB(255, 182, 255), 
                [2] = Color3.fromRGB(255, 105, 180), 
                [3] = Color3.fromRGB(255, 0, 251), 
                [4] = Color3.fromRGB(200, 0, 180), 
                [5] = Color3.fromRGB(255, 153, 253), 
                [6] = Color3.fromRGB(255, 153, 253), 
                [7] = Color3.fromRGB(239, 88, 239), 
                [8] = Color3.fromRGB(158, 69, 158)
            }
        }
    }, 
    Lava = {
        DisplayText = "Lava", 
        DisplayWithRichText = "<font color=\"#ff7700\">Lava</font>", 
        Order = 5, 
        Modifier = 5, 
        MainColor = Color3.fromRGB(255, 149, 0), 
        Icon = "rbxassetid://70800471498231", 
        Palettes = {
            [1] = {
                [1] = Color3.fromRGB(255, 94, 0), 
                [2] = Color3.fromRGB(232, 61, 18), 
                [3] = Color3.fromRGB(230, 33, 15), 
                [4] = Color3.fromRGB(255, 160, 0), 
                [5] = Color3.fromRGB(255, 112, 112), 
                [6] = Color3.fromRGB(255, 161, 144)
            }, 
            [2] = {
                [1] = Color3.fromRGB(255, 94, 0), 
                [2] = Color3.fromRGB(232, 61, 18), 
                [3] = Color3.fromRGB(230, 33, 15), 
                [4] = Color3.fromRGB(255, 160, 0), 
                [5] = Color3.fromRGB(255, 178, 0), 
                [6] = Color3.fromRGB(237, 194, 86), 
                [7] = Color3.fromRGB(145, 0, 27), 
                [8] = Color3.fromRGB(75, 0, 7)
            }
        }
    }, 
    Galaxy = {
        DisplayText = "Galaxy", 
        DisplayWithRichText = "<font color=\"#aa3cff\">Galaxy</font>", 
        Order = 6, 
        Modifier = 6, 
        MainColor = Color3.fromRGB(170, 60, 255), 
        Icon = "rbxassetid://139331671405138", 
        Palettes = {
            [1] = {
                [1] = Color3.fromRGB(170, 65, 210), 
                [2] = Color3.fromRGB(113, 0, 243), 
                [3] = Color3.fromRGB(87, 0, 186), 
                [4] = Color3.fromRGB(50, 20, 80), 
                [5] = Color3.fromRGB(80, 80, 80), 
                [6] = Color3.fromRGB(217, 157, 255)
            }, 
            [2] = {
                [1] = Color3.fromRGB(170, 65, 210), 
                [2] = Color3.fromRGB(113, 0, 243), 
                [3] = Color3.fromRGB(87, 0, 186), 
                [4] = Color3.fromRGB(50, 20, 80), 
                [5] = Color3.fromRGB(113, 0, 243), 
                [6] = Color3.fromRGB(170, 65, 210), 
                [7] = Color3.fromRGB(87, 0, 186), 
                [8] = Color3.fromRGB(50, 20, 80)
            }
        }
    }, 
    YinYang = {
        DisplayText = "Yin Yang", 
        UseRichText = true, 
        DisplayWithRichText = "<stroke color=\"#fff\" thickness=\"2\"><font color=\"#000\">Yin</font></stroke> <stroke color=\"#000\" thickness=\"2\"><font color=\"#fff\">Yang</font></stroke>", 
        Order = 7, 
        Modifier = 6.5, 
        MainColor = Color3.fromRGB(255, 255, 255), 
        Icon = "rbxassetid://112996178302302", 
        Palettes = {
            [1] = {
                [1] = Color3.fromRGB(255, 255, 255), 
                [2] = Color3.fromRGB(0, 0, 0), 
                [3] = Color3.fromRGB(172, 172, 172), 
                [4] = Color3.fromRGB(0, 0, 0), 
                [5] = Color3.fromRGB(0, 0, 0), 
                [6] = Color3.fromRGB(255, 255, 255)
            }, 
            [2] = {
                [1] = Color3.fromRGB(255, 255, 255), 
                [2] = Color3.fromRGB(0, 0, 0), 
                [3] = Color3.fromRGB(172, 172, 172), 
                [4] = Color3.fromRGB(0, 0, 0), 
                [5] = Color3.fromRGB(255, 255, 255), 
                [6] = Color3.fromRGB(0, 0, 0), 
                [7] = Color3.fromRGB(172, 172, 172), 
                [8] = Color3.fromRGB(0, 0, 0)
            }, 
            [3] = {
                [1] = Color3.fromRGB(0, 0, 0), 
                [2] = Color3.fromRGB(255, 255, 255), 
                [3] = Color3.fromRGB(0, 0, 0), 
                [4] = Color3.fromRGB(172, 172, 172), 
                [5] = Color3.fromRGB(0, 0, 0), 
                [6] = Color3.fromRGB(255, 255, 255)
            }, 
            [4] = {
                [1] = Color3.fromRGB(0, 0, 0), 
                [2] = Color3.fromRGB(255, 255, 255), 
                [3] = Color3.fromRGB(255, 255, 255), 
                [4] = Color3.fromRGB(172, 172, 172), 
                [5] = Color3.fromRGB(0, 0, 0), 
                [6] = Color3.fromRGB(255, 255, 255)
            }, 
            [5] = {
                [1] = Color3.fromRGB(0, 0, 0), 
                [2] = Color3.fromRGB(0, 0, 0), 
                [3] = Color3.fromRGB(0, 0, 0), 
                [4] = Color3.fromRGB(172, 172, 172), 
                [5] = Color3.fromRGB(0, 0, 0), 
                [6] = Color3.fromRGB(255, 255, 255)
            }, 
            [6] = {
                [1] = Color3.fromRGB(255, 255, 255), 
                [2] = Color3.fromRGB(255, 255, 255), 
                [3] = Color3.fromRGB(0, 0, 0), 
                [4] = Color3.fromRGB(172, 172, 172), 
                [5] = Color3.fromRGB(0, 0, 0), 
                [6] = Color3.fromRGB(255, 255, 255)
            }
        }
    }, 
    Radioactive = {
        DisplayText = "Radioactive", 
        UseRichText = false, 
        DisplayWithRichText = "<font color=\"#68f500\">Radioactive</font>", 
        Order = 7, 
        Modifier = 7.5, 
        MainColor = Color3.fromRGB(104, 245, 0), 
        Icon = "rbxassetid://134809510446754", 
        Palettes = {
            [1] = {
                [1] = Color3.fromRGB(51, 235, 0), 
                [2] = Color3.fromRGB(106, 177, 0), 
                [3] = Color3.fromRGB(44, 156, 0), 
                [4] = Color3.fromRGB(32, 80, 0), 
                [5] = Color3.fromRGB(70, 70, 70), 
                [6] = Color3.fromRGB(180, 255, 94), 
                [7] = Color3.fromRGB(106, 177, 0)
            }, 
            [2] = {
                [1] = Color3.fromRGB(57, 255, 20), 
                [2] = Color3.fromRGB(205, 255, 41), 
                [3] = Color3.fromRGB(0, 185, 90), 
                [4] = Color3.fromRGB(10, 40, 22), 
                [5] = Color3.fromRGB(57, 255, 20), 
                [6] = Color3.fromRGB(190, 255, 60), 
                [7] = Color3.fromRGB(0, 185, 90), 
                [8] = Color3.fromRGB(10, 40, 22)
            }, 
            [3] = {
                [1] = Color3.fromRGB(0, 185, 90), 
                [2] = Color3.fromRGB(10, 40, 22), 
                [3] = Color3.fromRGB(57, 255, 20), 
                [4] = Color3.fromRGB(190, 255, 60), 
                [5] = Color3.fromRGB(70, 70, 70), 
                [6] = Color3.fromRGB(217, 255, 157)
            }, 
            [4] = {
                [1] = Color3.fromRGB(40, 198, 0), 
                [2] = Color3.fromRGB(106, 177, 0), 
                [3] = Color3.fromRGB(44, 156, 0), 
                [4] = Color3.fromRGB(32, 80, 0), 
                [5] = Color3.fromRGB(70, 70, 70), 
                [6] = Color3.fromRGB(205, 255, 66)
            }, 
            [5] = {
                [1] = Color3.fromRGB(0, 204, 92), 
                [2] = Color3.fromRGB(136, 248, 0), 
                [3] = Color3.fromRGB(53, 198, 0), 
                [4] = Color3.fromRGB(44, 125, 0), 
                [5] = Color3.fromRGB(70, 70, 70), 
                [6] = Color3.fromRGB(205, 255, 66)
            }, 
            [6] = {
                [1] = Color3.fromRGB(51, 235, 0), 
                [2] = Color3.fromRGB(212, 255, 0), 
                [3] = Color3.fromRGB(44, 156, 0), 
                [4] = Color3.fromRGB(32, 80, 0), 
                [5] = Color3.fromRGB(70, 70, 70), 
                [6] = Color3.fromRGB(180, 255, 94), 
                [7] = Color3.fromRGB(153, 255, 0)
            }
        }
    }, 
    Cursed = {
        DisplayText = "Cursed", 
        UseRichText = false, 
        DisplayWithRichText = "<font color=\"#f53838\">Cursed</font>", 
        Order = 8, 
        Modifier = 8, 
        MainColor = Color3.fromRGB(245, 56, 56), 
        Icon = "rbxassetid://139160534192980", 
        Palettes = {
            [1] = {
                [1] = Color3.fromRGB(0, 0, 0), 
                [2] = Color3.fromRGB(177, 0, 0), 
                [3] = Color3.fromRGB(9, 9, 9), 
                [4] = Color3.fromRGB(11, 11, 11), 
                [5] = Color3.fromRGB(70, 70, 70), 
                [6] = Color3.fromRGB(255, 73, 73), 
                [7] = Color3.fromRGB(33, 33, 33)
            }, 
            [2] = {
                [1] = Color3.fromRGB(57, 255, 20), 
                [2] = Color3.fromRGB(205, 255, 41), 
                [3] = Color3.fromRGB(0, 185, 90), 
                [4] = Color3.fromRGB(10, 40, 22), 
                [5] = Color3.fromRGB(57, 255, 20), 
                [6] = Color3.fromRGB(190, 255, 60), 
                [7] = Color3.fromRGB(0, 185, 90), 
                [8] = Color3.fromRGB(10, 40, 22)
            }, 
            [3] = {
                [1] = Color3.fromRGB(0, 185, 90), 
                [2] = Color3.fromRGB(10, 40, 22), 
                [3] = Color3.fromRGB(57, 255, 20), 
                [4] = Color3.fromRGB(190, 255, 60), 
                [5] = Color3.fromRGB(70, 70, 70), 
                [6] = Color3.fromRGB(217, 255, 157)
            }, 
            [4] = {
                [1] = Color3.fromRGB(0, 0, 0), 
                [2] = Color3.fromRGB(177, 0, 0), 
                [3] = Color3.fromRGB(8, 8, 8), 
                [4] = Color3.fromRGB(80, 0, 0), 
                [5] = Color3.fromRGB(18, 18, 18), 
                [6] = Color3.fromRGB(255, 53, 53)
            }, 
            [5] = {
                [1] = Color3.fromRGB(0, 0, 0), 
                [2] = Color3.fromRGB(177, 0, 0), 
                [3] = Color3.fromRGB(9, 9, 9), 
                [4] = Color3.fromRGB(11, 11, 11), 
                [5] = Color3.fromRGB(70, 70, 70), 
                [6] = Color3.fromRGB(255, 73, 73), 
                [7] = Color3.fromRGB(33, 33, 33)
            }, 
            [6] = {
                [1] = Color3.fromRGB(0, 0, 0), 
                [2] = Color3.fromRGB(177, 0, 0), 
                [3] = Color3.fromRGB(9, 9, 9), 
                [4] = Color3.fromRGB(11, 11, 11), 
                [5] = Color3.fromRGB(70, 70, 70), 
                [6] = Color3.fromRGB(255, 73, 73), 
                [7] = Color3.fromRGB(33, 33, 33)
            }
        }
    }
};