return {
    Rewards = {
        {
            Type = "Animal", 
            Display = "<stroke><font color=\"#68f500\">Radioactive</font>\nSecret Lucky Block</stroke>", 
            Icon = "rbxassetid://118101095190167", 
            Index = "Secret Lucky Block", 
            Mutation = "Radioactive", 
            Weight = 0.5
        }, 
        {
            Type = "Cash-Pack", 
            Display = "Cash Pack #2", 
            Index = 3290160783, 
            Weight = 55.5
        }, 
        {
            Type = "Cash-Pack", 
            Display = "Cash Pack #3", 
            Index = 3290160857, 
            Weight = 34
        }, 
        {
            Type = "Item", 
            Display = "Radioactive Slap", 
            Icon = "rbxassetid://134911999156077", 
            Index = "Radioactive Slap", 
            Weight = 0.5
        }, 
        {
            Type = "Cash-Pack", 
            Display = "Cash Pack #5", 
            Index = 3290161030, 
            Weight = 7.5
        }, 
        {
            Type = "Server-Luck", 
            Icon = "rbxassetid://98903143335097", 
            Display = "2x Server Luck\n15m", 
            Index = 1, 
            Weight = 2
        }
    }, 
    AltRewards = {
        [4] = {
            Type = "Item", 
            Display = "Radioactive Airstrike", 
            Icon = "rbxassetid://73753077277254", 
            Index = "Radioactive Airstrike", 
            Weight = 0.1
        }
    }
};