return {
    Rewards = {
        {
            Type = "Animal", 
            Display = "Tralalero Tralala<br/>", 
            Icon = "rbxassetid://121208314705911", 
            Index = "Tralalero Tralala", 
            Mutation = "Rainbow", 
            Weight = 1
        }, 
        {
            Type = "Cash-Pack", 
            Display = "Cash Pack #2", 
            Index = 3290160783, 
            Weight = 55
        }, 
        {
            Type = "Cash-Pack", 
            Display = "Cash Pack #3", 
            Index = 3290160857, 
            Weight = 34
        }, 
        {
            Type = "Item", 
            Display = "Rainbow Slap", 
            Icon = "rbxassetid://76888105480836", 
            Index = "Rainbow Slap", 
            Weight = 0.5
        }, 
        {
            Type = "Cash-Pack", 
            Display = "Cash Pack #5", 
            Index = 3290161030, 
            Weight = 7.5
        }, 
        {
            Type = "Server-Luck", 
            Icon = "rbxassetid://98903143335097", 
            Display = "2x Server Luck\n15m", 
            Index = 1, 
            Weight = 2
        }
    }, 
    AltRewards = {
        [4] = {
            Type = "Item", 
            Display = "Rainbow Hammer", 
            Icon = "rbxassetid://139876541578910", 
            Index = "Rainbow Hammer", 
            Weight = 0.5
        }
    }
};