local l_ReplicatedStorage_0 = game:GetService("ReplicatedStorage");
local l_Packages_0 = l_ReplicatedStorage_0.Packages;
local _ = require(l_Packages_0.Synchronizer);
local _ = require(l_ReplicatedStorage_0.Datas.ServerData);
return {
    [3312891057] = {
        Display = "[Rainbow Machine] Fill Now", 
        Callback = function(_) --[[ Line: 41 ]] --[[ Name: Callback ]]
            return false;
        end, 
        Type = "RainbowMachine"
    }, 
    [3337520317] = {
        Display = "[Bubblegum Machine] Fill Now", 
        Callback = function(_) --[[ Line: 55 ]] --[[ Name: Callback ]]
            return false;
        end, 
        Type = "RainbowMachine"
    }, 
    [3312944986] = {
        Display = "1x Spin (Rainbow Wheel)", 
        Identifier = "x1", 
        Type = "RainbowSpinWheel", 
        Value = 1
    }, 
    [3312945232] = {
        Display = "1x Spin (Rainbow Wheel) DISCOUNT", 
        Identifier = "x1", 
        Type = "RainbowSpinWheel", 
        Value = 1
    }, 
    [3312945488] = {
        Display = "3x Spins (Rainbow Wheel)", 
        Identifier = "x3", 
        Type = "RainbowSpinWheel", 
        Value = 3
    }, 
    [3312944807] = {
        Display = "10x Spins (Rainbow Wheel)", 
        Identifier = "x10", 
        Type = "RainbowSpinWheel", 
        Value = 10
    }, 
    [3307371795] = {
        Display = "1x Spin (Bloodmoon Wheel)", 
        Identifier = "x1", 
        Type = "BloodmoonWheelSpin", 
        Value = 1
    }, 
    [3307372046] = {
        Display = "1x Spin (Bloodmoon Wheel) DISCOUNT", 
        Identifier = "x1", 
        Type = "BloodmoonWheelSpin", 
        Value = 1
    }, 
    [3307372342] = {
        Display = "3x Spins (Bloodmoon Wheel)", 
        Identifier = "x3", 
        Type = "BloodmoonWheelSpin", 
        Value = 3
    }, 
    [3307372798] = {
        Display = "10x Spins (Bloodmoon Wheel)", 
        Identifier = "x10", 
        Type = "BloodmoonWheelSpin", 
        Value = 10
    }, 
    [3322567440] = {
        Display = "1x Spin (Candy Wheel)", 
        Identifier = "x1", 
        Type = "CandyWheelSpin", 
        Value = 1
    }, 
    [3322568083] = {
        Display = "1x Spin (Candy Wheel) DISCOUNT", 
        Identifier = "x1", 
        Type = "CandyWheelSpin", 
        Value = 1
    }, 
    [3322567771] = {
        Display = "3x Spins (Candy Wheel)", 
        Identifier = "x3", 
        Type = "CandyWheelSpin", 
        Value = 3
    }, 
    [3322567871] = {
        Display = "10x Spins (Candy Wheel)", 
        Identifier = "x10", 
        Type = "CandyWheelSpin", 
        Value = 10
    }, 
    [3345489415] = {
        Display = "1x Spin (Molten Wheel)", 
        Identifier = "x1", 
        Type = "MoltenWheelSpin", 
        Value = 1
    }, 
    [3345489701] = {
        Display = "1x Spin (Molten Wheel) DISCOUNT", 
        Identifier = "x1", 
        Type = "MoltenWheelSpin", 
        Value = 1
    }, 
    [3345489943] = {
        Display = "3x Spins (Molten Wheel)", 
        Identifier = "x3", 
        Type = "MoltenWheelSpin", 
        Value = 3
    }, 
    [3345489151] = {
        Display = "10x Spins (Molten Wheel)", 
        Identifier = "x10", 
        Type = "MoltenWheelSpin", 
        Value = 10
    }, 
    [3377020181] = {
        Display = "1x Spin (Galaxy Wheel)", 
        Identifier = "x1", 
        Type = "GalaxyWheelSpin", 
        Value = 1
    }, 
    [3377020567] = {
        Display = "1x Spin (Galaxy Wheel) DISCOUNT", 
        Identifier = "x1", 
        Type = "GalaxyWheelSpin", 
        Value = 1
    }, 
    [3377021022] = {
        Display = "3x Spins (Galaxy Wheel)", 
        Identifier = "x3", 
        Type = "GalaxyWheelSpin", 
        Value = 3
    }, 
    [3377020761] = {
        Display = "10x Spins (Galaxy Wheel)", 
        Identifier = "x10", 
        Type = "GalaxyWheelSpin", 
        Value = 10
    }, 
    [3414123796] = {
        Display = "1x Spin (Yin Yang Wheel)", 
        Identifier = "x1", 
        Type = "YinYangWheelSpin", 
        Value = 1
    }, 
    [3414123985] = {
        Display = "1x Spin (Yin Yang Wheel) DISCOUNT", 
        Identifier = "x1", 
        Type = "YinYangWheelSpin", 
        Value = 1
    }, 
    [3414124199] = {
        Display = "3x Spins (Yin Yang Wheel)", 
        Identifier = "x3", 
        Type = "YinYangWheelSpin", 
        Value = 3
    }, 
    [3414124509] = {
        Display = "10x Spins (Yin Yang Wheel)", 
        Identifier = "x10", 
        Type = "YinYangWheelSpin", 
        Value = 10
    }, 
    [3456071068] = {
        Display = "1x Spin (Radioactive Wheel)", 
        Identifier = "x1", 
        Type = "RadioactiveWheelSpin", 
        Value = 1
    }, 
    [3456071066] = {
        Display = "1x Spin (Radioactive Wheel) DISCOUNT", 
        Identifier = "x1", 
        Type = "RadioactiveWheelSpin", 
        Value = 1
    }, 
    [3456071067] = {
        Display = "3x Spins (Radioactive Wheel)", 
        Identifier = "x3", 
        Type = "RadioactiveWheelSpin", 
        Value = 3
    }, 
    [3456071065] = {
        Display = "10x Spins (Radioactive Wheel)", 
        Identifier = "x10", 
        Type = "RadioactiveWheelSpin", 
        Value = 10
    }, 
    [3488386426] = {
        Display = "1x Spin (Christmas Wheel)", 
        Identifier = "x1", 
        Type = "ChristmasWheelSpin", 
        Value = 1
    }, 
    [3488386429] = {
        Display = "1x Spin (Christmas Wheel) DISCOUNT", 
        Identifier = "x1", 
        Type = "ChristmasWheelSpin", 
        Value = 1
    }, 
    [3488386430] = {
        Display = "3x Spin (Christmas Wheel)", 
        Identifier = "x3", 
        Type = "ChristmasWheelSpin", 
        Value = 3
    }, 
    [3488386428] = {
        Display = "10x Spin (Christmas Wheel)", 
        Identifier = "x10", 
        Type = "ChristmasWheelSpin", 
        Value = 10
    }, 
    [3499648585] = {
        Display = "1x Spin (Cursed Wheel)", 
        Identifier = "x1", 
        Type = "CursedWheelSpin", 
        Value = 1
    }, 
    [3499648586] = {
        Display = "1x Spin (Cursed Wheel) DISCOUNT", 
        Identifier = "x1", 
        Type = "CursedWheelSpin", 
        Value = 1
    }, 
    [3499648590] = {
        Display = "3x Spins (Cursed Wheel)", 
        Identifier = "x3", 
        Type = "CursedWheelSpin", 
        Value = 3
    }, 
    [3499648587] = {
        Display = "10x Spins (Cursed Wheel)", 
        Identifier = "x10", 
        Type = "CursedWheelSpin", 
        Value = 10
    }, 
    [3296448740] = {
        Display = "2x Server Luck", 
        Type = "ServerLuck", 
        Index = 1
    }, 
    [3296448922] = {
        Display = "4x Server Luck", 
        Type = "ServerLuck", 
        Index = 2
    }, 
    [3296367737] = {
        Display = "VIP", 
        Type = "GamepassProduct", 
        GiftProduct = 3484585104, 
        GiftProductNoRegional = 3296367737
    }, 
    [3296367604] = {
        Display = "Admin Commands", 
        Attribute = "AdminCommands", 
        Type = "GamepassProduct", 
        GiftProduct = 3484585108, 
        GiftProductNoRegional = 3296367604
    }, 
    [3296367825] = {
        Display = "2x Money", 
        Attribute = "2xMoney", 
        Type = "GamepassProduct", 
        GiftProduct = 3484585101, 
        GiftProductNoRegional = 3296367825
    }, 
    [3290160693] = {
        Display = "Cash Pack #1", 
        Type = "Coins", 
        Value = 3000, 
        GiftProduct = 3484554689, 
        GiftProductNoRegional = 3484554697
    }, 
    [3290160783] = {
        Display = "Cash Pack #2", 
        Type = "Coins", 
        Value = 25000, 
        GiftProduct = 3484554693, 
        GiftProductNoRegional = 3484554695
    }, 
    [3290160857] = {
        Display = "Cash Pack #3", 
        Type = "Coins", 
        Value = 100000, 
        GiftProduct = 3484554718, 
        GiftProductNoRegional = 3484554700
    }, 
    [3290160954] = {
        Display = "Cash Pack #4", 
        Type = "Coins", 
        Value = 500000, 
        GiftProduct = 3484554694, 
        GiftProductNoRegional = 3484554723
    }, 
    [3290161030] = {
        Display = "Cash Pack #5", 
        Type = "Coins", 
        Value = 1000000, 
        GiftProduct = 3484554719, 
        GiftProductNoRegional = 3484554724
    }, 
    [3290152459] = {
        Display = "Blackhole Slap", 
        Type = "Item", 
        Icon = "rbxassetid://88520285647604", 
        GiftProduct = 3484554727, 
        GiftProductNoRegional = 3484554725
    }, 
    [3290152552] = {
        Display = "Laser Gun", 
        Type = "Item", 
        Icon = "rbxassetid://127461267233201", 
        GiftProduct = 3484554707, 
        GiftProductNoRegional = 3484554701
    }, 
    [3290152513] = {
        Display = "Flying Carpet", 
        Type = "Item", 
        GiftProduct = 3484554722, 
        GiftProductNoRegional = 3484554691
    }, 
    [3442807551] = {
        Display = "Witch's Broom", 
        Type = "Item"
    }, 
    [3483721069] = {
        Display = "Santa's Sleigh", 
        Type = "Item", 
        Icon = "rbxassetid://106575011463424", 
        GiftProduct = 3484554698, 
        GiftProductNoRegional = 3484554726
    }, 
    [3290152611] = {
        Display = "Ban Hammer", 
        Type = "Item", 
        Icon = "rbxassetid://113735454516185", 
        GiftProduct = 3484554720, 
        GiftProductNoRegional = 3484554717
    }, 
    [1227013099] = {
        Display = "Admin Commands", 
        Attribute = "AdminCommands", 
        Type = "Gamepass"
    }, 
    [1229510262] = {
        Display = "VIP", 
        Type = "Gamepass"
    }, 
    [1228591447] = {
        Display = "2x Money", 
        Attribute = "2xMoney", 
        Type = "Gamepass"
    }, 
    [3290334159] = {
        Display = "Starter Pack", 
        Type = "Pack", 
        Rewards = {
            Items = {
                "Blackhole Slap", 
                "Coil Combo"
            }, 
            Animals = {
                "Brr Brr Patapim"
            }, 
            Coins = 1000
        }, 
        GiftProduct = 3484554690, 
        GiftProductNoRegional = 3484554721
    }, 
    [3442292161] = {
        Display = "Halloween Pack", 
        Type = "Pack", 
        Rewards = {
            Items = {
                "Witch's Broom"
            }, 
            Animals = {
                "Spooky Lucky Block", 
                "Spooky Lucky Block", 
                "Spooky Lucky Block"
            }, 
            Coins = 0
        }
    }, 
    [3481756179] = {
        Display = "Santa's Sleigh Pack", 
        Type = "Pack", 
        Icon = "rbxassetid://106575011463424", 
        Rewards = {
            Items = {
                "Santa's Sleigh"
            }, 
            Animals = {
                "Premium Festive Lucky Block", 
                "Premium Festive Lucky Block"
            }, 
            Coins = 0
        }, 
        GiftProduct = 3484576546, 
        GiftProductNoRegional = 3484576544
    }, 
    [3483709817] = {
        Display = "Gingerbread Base Pack", 
        Type = "Pack", 
        Icon = "rbxassetid://126481609231646", 
        Rewards = {
            Items = {}, 
            Animals = {
                "Premium Festive Lucky Block"
            }, 
            Base = {
                "Gingerbread"
            }, 
            Coins = 0
        }, 
        GiftProduct = 3484576542, 
        GiftProductNoRegional = 3484576545
    }, 
    [3483736285] = {
        Display = "Gingerbread Base", 
        Type = "Base", 
        Icon = "rbxassetid://126481609231646", 
        Value = "Gingerbread", 
        GiftProduct = 3484554704, 
        GiftProductNoRegional = 3484554692
    }, 
    [3301638537] = {
        Display = "Unlock Base", 
        Type = "UnlockBase"
    }, 
    [3312023518] = {
        Display = "Unlock First Floor", 
        Type = "UnlockBase"
    }, 
    [3312023590] = {
        Display = "Unlock Second Floor", 
        Type = "UnlockBase"
    }, 
    [3312023715] = {
        Display = "Unlock Third Floor", 
        Type = "UnlockBase"
    }, 
    [3329528158] = {
        Display = "Mythic Lucky Block", 
        Type = "LuckyBlock", 
        Value = "Mythic Lucky Block"
    }, 
    [3329527999] = {
        Display = "Brainrot God Lucky Block", 
        Type = "LuckyBlock", 
        Value = "Brainrot God Lucky Block"
    }, 
    [3329528437] = {
        Display = "Secret Lucky Block", 
        Type = "LuckyBlock", 
        Value = "Secret Lucky Block"
    }, 
    [3437062543] = {
        Display = "+3 Secret Lucky Block", 
        Type = "LuckyBlock", 
        Value = "Secret Lucky Block", 
        Amount = 3
    }, 
    [3437979356] = {
        Display = "+8 Secret Lucky Block", 
        Type = "LuckyBlock", 
        Value = "Secret Lucky Block", 
        Amount = 8
    }, 
    [3437989614] = {
        Display = "+1 Secret, Brainrot God, Mythic Lucky Block", 
        Type = "LuckyBlock", 
        Value = {
            "Secret Lucky Block", 
            "Brainrot God Lucky Block", 
            "Mythic Lucky Block"
        }
    }, 
    [3478819642] = {
        Display = "Premium Festive Lucky Block", 
        Type = "LuckyBlock", 
        Value = "Premium Festive Lucky Block"
    }, 
    [3478819641] = {
        Display = "+3 Premium Festive Lucky Block", 
        Type = "LuckyBlock", 
        Value = "Premium Festive Lucky Block", 
        Amount = 3
    }, 
    [3478819648] = {
        Display = "+10 Premium Festive Lucky Block", 
        Type = "LuckyBlock", 
        Value = "Premium Festive Lucky Block", 
        Amount = 10
    }, 
    [3450973929] = {
        Display = "Cupcake Koala", 
        Type = "MerchantBrainrot", 
        Value = "Cupcake Koala"
    }, 
    [3450973937] = {
        Display = "Doi Doi Do", 
        Type = "MerchantBrainrot", 
        Value = "Doi Doi Do"
    }, 
    [3450973935] = {
        Display = "Clickerino Crabo", 
        Type = "MerchantBrainrot", 
        Value = "Clickerino Crabo"
    }, 
    [3450973930] = {
        Display = "Stoppo Luminino", 
        Type = "MerchantBrainrot", 
        Value = "Stoppo Luminino"
    }, 
    [3450973932] = {
        Display = "Money Money Man", 
        Type = "MerchantBrainrot", 
        Value = "Money Money Man"
    }, 
    [3450973934] = {
        Display = "Noo La Polizia", 
        Type = "MerchantBrainrot", 
        Value = "Noo La Polizia"
    }, 
    [3450973933] = {
        Display = "Pirulitoita Bicicleteira", 
        Type = "MerchantBrainrot", 
        Value = "Pirulitoita Bicicleteira"
    }, 
    [3450973936] = {
        Display = "Los Puggies", 
        Type = "MerchantBrainrot", 
        Value = "Los Puggies"
    }, 
    [3354160217] = {
        Display = "Reveal Now", 
        Type = "FuseMachineRevealNow", 
        Callback = function(v6) --[[ Line: 656 ]] --[[ Name: Callback ]]
            local l_ServerScriptService_0 = game:GetService("ServerScriptService");
            return require(l_ServerScriptService_0.Services.FuseMachineService):PurchaseRevealNow(v6);
        end, 
        GiftProduct = 3484554699, 
        GiftProductNoRegional = 3484554702
    }, 
    [3483927303] = {
        Display = "Fuse Machine Luck", 
        Type = "FuseMachineLuck", 
        Callback = function(_) --[[ Line: 668 ]] --[[ Name: Callback ]]
            local l_ServerScriptService_1 = game:GetService("ServerScriptService");
            return require(l_ServerScriptService_1.Services.FuseMachineService):AddLuck();
        end
    }, 
    [3394964472] = {
        Display = "Craft Now - Epic", 
        Type = "CraftingMachineClaimNow", 
        Callback = function(v10) --[[ Line: 679 ]] --[[ Name: Callback ]]
            local l_ServerScriptService_2 = game:GetService("ServerScriptService");
            return require(l_ServerScriptService_2.Services.CraftingMachineService):PurchaseCraftNow(v10, "Epic");
        end
    }, 
    [3394964604] = {
        Display = "Craft Now - Legendary", 
        Type = "CraftingMachineClaimNow", 
        Callback = function(v12) --[[ Line: 688 ]] --[[ Name: Callback ]]
            local l_ServerScriptService_3 = game:GetService("ServerScriptService");
            return require(l_ServerScriptService_3.Services.CraftingMachineService):PurchaseCraftNow(v12, "Legendary");
        end
    }, 
    [3394964736] = {
        Display = "Craft Now - Mythic", 
        Type = "CraftingMachineClaimNow", 
        Callback = function(v14) --[[ Line: 697 ]] --[[ Name: Callback ]]
            local l_ServerScriptService_4 = game:GetService("ServerScriptService");
            return require(l_ServerScriptService_4.Services.CraftingMachineService):PurchaseCraftNow(v14, "Mythic");
        end
    }, 
    [3394965881] = {
        Display = "Craft Now - Brainrot God", 
        Type = "CraftingMachineClaimNow", 
        Callback = function(v16) --[[ Line: 706 ]] --[[ Name: Callback ]]
            local l_ServerScriptService_5 = game:GetService("ServerScriptService");
            return require(l_ServerScriptService_5.Services.CraftingMachineService):PurchaseCraftNow(v16, "Brainrot God");
        end
    }, 
    [3394969112] = {
        Display = "Craft Now - Secret", 
        Type = "CraftingMachineClaimNow", 
        Callback = function(v18) --[[ Line: 715 ]] --[[ Name: Callback ]]
            local l_ServerScriptService_6 = game:GetService("ServerScriptService");
            return require(l_ServerScriptService_6.Services.CraftingMachineService):PurchaseCraftNow(v18, "Secret");
        end
    }, 
    [3467217692] = {
        Display = "Recover [1]", 
        Type = "AdventCalendarRecover", 
        Callback = function(v20) --[[ Line: 726 ]] --[[ Name: Callback ]]
            local l_ServerScriptService_7 = game:GetService("ServerScriptService");
            return (require(l_ServerScriptService_7.Services.AdventService):Recover(v20));
        end
    }, 
    [3467217695] = {
        Display = "Recover [2]", 
        Type = "AdventCalendarRecover", 
        Callback = function(v22) --[[ Line: 736 ]] --[[ Name: Callback ]]
            local l_ServerScriptService_8 = game:GetService("ServerScriptService");
            return (require(l_ServerScriptService_8.Services.AdventService):Recover(v22));
        end
    }, 
    [3467217689] = {
        Display = "Recover [3]", 
        Type = "AdventCalendarRecover", 
        Callback = function(v24) --[[ Line: 746 ]] --[[ Name: Callback ]]
            local l_ServerScriptService_9 = game:GetService("ServerScriptService");
            return (require(l_ServerScriptService_9.Services.AdventService):Recover(v24));
        end
    }, 
    [3467217690] = {
        Display = "Recover [4]", 
        Type = "AdventCalendarRecover", 
        Callback = function(v26) --[[ Line: 756 ]] --[[ Name: Callback ]]
            local l_ServerScriptService_10 = game:GetService("ServerScriptService");
            return (require(l_ServerScriptService_10.Services.AdventService):Recover(v26));
        end
    }, 
    [3467217694] = {
        Display = "Recover [5]", 
        Type = "AdventCalendarRecover", 
        Callback = function(v28) --[[ Line: 766 ]] --[[ Name: Callback ]]
            local l_ServerScriptService_11 = game:GetService("ServerScriptService");
            return (require(l_ServerScriptService_11.Services.AdventService):Recover(v28));
        end
    }, 
    [3467217691] = {
        Display = "Recover [6]", 
        Type = "AdventCalendarRecover", 
        Callback = function(v30) --[[ Line: 776 ]] --[[ Name: Callback ]]
            local l_ServerScriptService_12 = game:GetService("ServerScriptService");
            return (require(l_ServerScriptService_12.Services.AdventService):Recover(v30));
        end
    }, 
    [3467217693] = {
        Display = "Recover [7]", 
        Type = "AdventCalendarRecover", 
        Callback = function(v32) --[[ Line: 786 ]] --[[ Name: Callback ]]
            local l_ServerScriptService_13 = game:GetService("ServerScriptService");
            return (require(l_ServerScriptService_13.Services.AdventService):Recover(v32));
        end
    }, 
    [3477983793] = {
        Display = "Festive 67", 
        Type = "MerchShopItem", 
        Callback = function(v34) --[[ Line: 798 ]] --[[ Name: Callback ]]
            local l_ServerScriptService_14 = game:GetService("ServerScriptService");
            return (require(l_ServerScriptService_14.Services.MerchShopService):AwardItem(v34, "Festive 67"));
        end
    }, 
    [3487835433] = {
        Display = "Los Jolly Combinasionas", 
        Type = "SantaMerchantBrainrot", 
        Value = "Los Jolly Combinasionas"
    }, 
    [3487835436] = {
        Display = "Money Money Reindeer", 
        Type = "SantaMerchantBrainrot", 
        Value = "Money Money Reindeer"
    }, 
    [3487835435] = {
        Display = "Jolly Jolly Sahur", 
        Type = "SantaMerchantBrainrot", 
        Value = "Jolly Jolly Sahur"
    }, 
    [3487835440] = {
        Display = "Ginger Gerat", 
        Type = "SantaMerchantBrainrot", 
        Value = "Ginger Gerat"
    }
};