return {
    Rewards = {
        {
            Type = "Animal", 
            Display = "<stroke color='#fff' thickness='2'><font color='#000'>Yin</font></stroke> <stroke thickness='2'><font color='#fff'>Yang</font>\nBisonte Giuppitere\n<font color='#2bff5c'>$2.4M/s</font></stroke>", 
            Icon = "rbxassetid://78877057270585", 
            Index = "Bisonte Giuppitere", 
            Mutation = "YinYang", 
            Weight = 1
        }, 
        {
            Type = "Cash-Pack", 
            Display = "Cash Pack #2", 
            Index = 3290160783, 
            Weight = 55
        }, 
        {
            Type = "Cash-Pack", 
            Display = "Cash Pack #3", 
            Index = 3290160857, 
            Weight = 34
        }, 
        {
            Type = "Item", 
            Display = "Yin Yang Slap", 
            Icon = "rbxassetid://72523518394942", 
            Index = "Yin Yang Slap", 
            Weight = 0.5
        }, 
        {
            Type = "Cash-Pack", 
            Display = "Cash Pack #5", 
            Index = 3290161030, 
            Weight = 7.5
        }, 
        {
            Type = "Server-Luck", 
            Icon = "rbxassetid://98903143335097", 
            Display = "2x Server Luck\n15m", 
            Index = 1, 
            Weight = 2
        }
    }, 
    AltRewards = {
        [4] = {
            Type = "Item", 
            Display = "Yin Yang Lamp", 
            Icon = "rbxassetid://106398585307279", 
            Index = "Yin Yang Lamp", 
            Weight = 0.1
        }
    }
};